version: "3.9"


services:
  db:
    image: postgres:16
    container_name: new_post
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yandiev
      POSTGRES_DB: yandiev
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: new_app
    ports:
      - "2030:3000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  postgres_data:
    
  
